---
name: Build linux wheels

# yamllint disable-line rule:truthy
on: [push, pull_request]

env:
    SETUPTOOLS_ENABLE_FEATURES: legacy-editable

jobs:
    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4

            - name: Build wheels
              uses: pypa/cibuildwheel@v2.12.3
              env:
                  CIBW_BUILD: cp38-* cp39-* cp310-* cp311-*
                  CIBW_SKIP: pp* cp36-* cp37-*

                  CIBW_BEFORE_BUILD_LINUX: |
                      yum upgrade -y || apt-get update -y || apk update ;
                      yum upgrade -y hdf5-devel openblas-devel || apt-get install -y libhdf5-dev libopenblas-dev || apk add --update hdf5-dev openblas-dev

                  CIBW_TEST_REQUIRES: pytest
                  CIBW_TEST_COMMAND: "cd {project}; pytest"

            - name: Build source distribution
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install --upgrade 'setuptools>=45'
                  python3 -m pip install --upgrade 'setuptools-scm>=6.2'
                  python3 -m pip install --upgrade wheel
                  python3 -m pip install --upgrade numpy
                  python3 setup.py sdist

            - name: Upload
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_WDMTOOLBOX_TOKEN }}
              run:
                  python3 -m pip install --upgrade twine
                  twine upload --verbose --skip-existing dist/*
                  twine upload --verbose --skip-existing wheelhouse/*.whl
